DROP PROCEDURE IF EXISTS PROC_ALTER_TABLE_DROP_COLUMN;
DELIMITER //
CREATE PROCEDURE PROC_ALTER_TABLE_DROP_COLUMN(_table VARCHAR(64),
									_field varchar(64), 
									_bd varchar(64))
BEGIN
	DECLARE _stmt VARCHAR(1024);

	IF EXISTS(	
		SELECT COLUMN_NAME
		FROM information_schema.COLUMNS 
		WHERE 
		TABLE_SCHEMA = _bd
		AND TABLE_NAME = _table
		AND COLUMN_NAME = _field) 
	THEN
		SET @SQL :=CONCAT('ALTER TABLE ', _table,' DROP COLUMN ',_field);
		PREPARE _stmt FROM @SQL;
		EXECUTE _stmt;
		DEALLOCATE PREPARE _stmt;
	ELSE
		SELECT 'NO EXISTE LA COLUMNA';
	END IF ;

	#SELECT @SQL;

	

END//
